permit nopass player as root cmd evsieve
permit nopass player as root cmd /usr/bin/evsieve
permit nopass player as root cmd appctl
permit nopass player as root cmd /usr/local/bin/appctl
permit nopass player as root cmd /usr/local/bin/toggle-screen.sh
permit nopass player as root cmd /usr/local/bin/persist-settings.sh
permit nopass player as root cmd /usr/local/bin/power-profile.sh
permit nopass player as root cmd /usr/local/bin/set-time.sh
permit nopass player as root cmd /usr/local/bin/external-card.sh
permit nopass player as root cmd /usr/local/bin/power-action.sh
permit nopass player as root cmd /usr/local/bin/audio-output.sh
