permit nopass player as root cmd /sbin/poweroff
permit nopass player as root cmd /sbin/reboot
permit nopass player as root cmd evsieve
permit nopass player as root cmd /usr/bin/evsieve
permit nopass player as root cmd appctl
permit nopass player as root cmd /usr/local/bin/appctl
