#!/bin/sh
case "$1" in
  start)
      alsactl restore -f /var/lib/alsa/asound.state
      /usr/local/bin/audio-output.sh apply
      /usr/local/bin/hud-status.sh
  ;;
  stop)
      alsactl --file /var/lib/alsa/asound.state store
esac
