KEY_VOLUMEUP+BTN_MODE           1    /usr/local/bin/brightstep.sh up
KEY_VOLUMEDOWN+BTN_MODE         1    /usr/local/bin/brightstep.sh down
KEY_VOLUMEUP+BTN_MODE           2    /usr/local/bin/brightstep.sh up
KEY_VOLUMEDOWN+BTN_MODE         2    /usr/local/bin/brightstep.sh down
BTN_MODE+BTN_START+BTN_SELECT   1    /usr/local/bin/appctl kill-application
BTN_START+BTN_MODE+BTN_SELECT   1    /usr/local/bin/appctl kill-application
BTN_SELECT+BTN_MODE+BTN_START   1    /usr/local/bin/appctl kill-application
BTN_START+BTN_SELECT            1    /usr/local/bin/appctl stop-application
BTN_SELECT+BTN_START            1    /usr/local/bin/appctl stop-application
BTN_DPAD_UP+BTN_MODE            1    /usr/local/bin/toggle-hud.sh
BTN_MODE+BTN_DPAD_UP            1    /usr/local/bin/toggle-hud.sh
BTN_DPAD_DOWN+BTN_MODE          1    /usr/local/bin/audio-output.sh toggle
BTN_MODE+BTN_DPAD_DOWN          1    /usr/local/bin/audio-output.sh toggle
